"""Private auditable voting — commit-reveal with nullifiers (Phase 7.2 + 12).

This is a pragmatic first step toward MACI-style private voting for the
constitutional swarm. We use a classic commit-reveal scheme with
nullifiers to get three properties without heavy ZK machinery:

1. **Ballot privacy during collection** — commitments hide the vote
   until the reveal phase, so no voter can adaptively counter-vote.
2. **Eligibility and double-vote prevention** — every ballot is bound to
   a registered Ed25519 public key, and its deterministic nullifier is
   derived from that key and the epoch/subject. One eligible key can
   contribute at most one counted ballot.
3. **Auditable tally** — the tally is computed only from revealed
   votes whose commit verifies, and everyone can recompute it from the
   public log.

This is *not* full MACI: it does not hide the vote after reveal, and
relies on voters revealing.

**Phase 12 — validity-proof scaffold (v2 record).**  Commits can now
optionally carry a ``validity_proof`` attesting that the committed
choice is well-formed (membership in :class:`BallotChoice` and
signature-binding) *before* the reveal phase. The
:class:`ValidityProver` ``Protocol`` is the plug-in point for a future
Groth16/PLONK backend. The default :class:`HashCommitmentProver` is a
wire-format scaffold only: it is neither zero-knowledge nor evidence
that a hidden valid opening exists, and strict mode always rejects it.

Commit digests and nullifiers are voter-bound. Ballots generated by
older releases must be regenerated; old and new commit/reveal pairs
cannot be mixed.

Commit format (stable, JSON-serializable)::

    {
      "version": 1 | 2,
      "epoch": "<bytes hex>",
      "subject": "<bytes hex>",
      "voter": "<ed25519 pubkey hex>",
      "commit": "<sha256 hex>",
      "nullifier": "<sha256 hex>",
      "signature": "<ed25519 sig hex>",
      # v2 only:
      "proof_scheme": "<scheme-id | null>",
      "validity_proof": "<hex | null>",
    }

Reveal format::

    {
      "version": 1,
      "commit": "<sha256 hex>",
      "choice": "yea|nay|abstain",
      "nonce": "<hex>",
      "signature": "<ed25519 sig hex>",
    }

The tally function takes the set of commits and reveals and produces
a deterministic, auditable :class:`PrivateTally`.
"""

from __future__ import annotations

import hashlib
import json
import secrets
from threading import Lock
from types import MappingProxyType
from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Protocol, runtime_checkable

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)

__all__ = [
    "BallotChoice",
    "CommitRecord",
    "DoubleVoteError",
    "HashCommitmentProver",
    "InvalidCommitError",
    "InvalidRevealError",
    "InvalidValidityProofError",
    "MissingRevealError",
    "PrivateBallotBox",
    "PrivateTally",
    "RevealRecord",
    "ValidityProver",
    "ValidityStatement",
    "ValidityWitness",
    "ZKSnarkProver",
    "build_commit",
    "build_reveal",
    "compute_nullifier",
    "tally",
]

# Highest version this module emits; tally accepts anything in _SUPPORTED_VERSIONS.
_RECORD_VERSION = 1  # default write-version when no prover is supplied
_V2_VERSION = 2
_SUPPORTED_VERSIONS: frozenset[int] = frozenset({_RECORD_VERSION, _V2_VERSION})


class BallotChoice(StrEnum):
    """Canonical ballot choices. Extend cautiously — domain is part
    of the commit digest, so adding a choice changes every commit."""

    YEA = "yea"
    NAY = "nay"
    ABSTAIN = "abstain"


class PrivateVotingError(Exception):
    """Base class for private voting errors."""


class InvalidCommitError(PrivateVotingError):
    """Raised when a commit record fails validation."""


class InvalidRevealError(PrivateVotingError):
    """Raised when a reveal record does not match its commit."""


class DoubleVoteError(PrivateVotingError):
    """Raised when a duplicate nullifier is seen in the same epoch."""


class MissingRevealError(PrivateVotingError):
    """Raised when tally is invoked while some commits are unrevealed."""


class InvalidValidityProofError(PrivateVotingError):
    """Raised when a v2 commit's validity proof fails to verify."""


# ---------------------------------------------------------------------------
# Validity-proof plug-in surface (Phase 12)
#
# The default :class:`HashCommitmentProver` is **not** zero-knowledge — it
# binds a domain-separated hash of (scheme-id, commit-digest, voter pubkey,
# nullifier, choice) and stores that hash as the "proof". This establishes
# the v2 wire format and the tally verification path so a real SNARK
# backend can replace it later without breaking clients. A proper
# :class:`ZKSnarkProver` (Groth16/PLONK over the BallotChoice membership
# circuit) is left as a documented future extension; shipping it requires
# picking a SNARK toolchain and is explicitly out of scope here.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ValidityStatement:
    """Public statement the validity proof attests to.

    A valid v2 commit says: "the preimage of ``commit`` is some
    :class:`BallotChoice`, and the same voter key signed it."
    """

    epoch: bytes
    subject: bytes
    voter: bytes
    commit: bytes
    nullifier: bytes


@dataclass(frozen=True)
class ValidityWitness:
    """Private witness held by the voter (never published)."""

    choice: BallotChoice
    nonce: bytes
    voter_secret: bytes


@runtime_checkable
class ValidityProver(Protocol):
    """Pluggable prover/verifier for v2 commit validity proofs.

    Implementations MUST be deterministic on ``(statement, witness)``
    for reproducibility in tests and audit logs. ``verify`` MUST return
    ``False`` rather than raise on malformed input; raise only on
    outright protocol violations (wrong scheme id, etc.).
    """

    scheme_id: str
    provides_validity_assurance: bool

    def prove(
        self, statement: ValidityStatement, witness: ValidityWitness
    ) -> bytes:  # pragma: no cover - Protocol
        ...

    def verify(
        self, statement: ValidityStatement, proof: bytes
    ) -> bool:  # pragma: no cover - Protocol
        ...


@dataclass(frozen=True)
class HashCommitmentProver:
    """Hash-based wire-format scaffold with zero validity assurance.

    The "proof" is a domain-separated SHA-256 digest of
    ``(scheme_id, statement fields, choice)``. Anyone who knows the
    choice can recompute it — so this is NOT a ZK proof; it only adds
    a tamper-evident binding that non-strict v2 readers can verify. It
    is never accepted as a validity proof in strict mode, even if its
    scheme id is changed.
    """

    scheme_id: str = "hash-commitment-v1"
    provides_validity_assurance: bool = field(default=False, init=False)

    def prove(self, statement: ValidityStatement, witness: ValidityWitness) -> bytes:
        try:
            witness_choice = BallotChoice(witness.choice)
        except (TypeError, ValueError) as exc:
            raise ValueError("witness.choice must be a BallotChoice member") from exc
        return _digest(
            b"acgs-validity-hashcommit-v1",
            self.scheme_id.encode("ascii"),
            statement.epoch,
            statement.subject,
            statement.voter,
            statement.commit,
            statement.nullifier,
            witness_choice.value.encode("ascii"),
        )

    def verify(self, statement: ValidityStatement, proof: bytes) -> bool:
        # Non-ZK verifier: re-derive the expected digest for EVERY choice
        # and accept if any matches. This keeps verification side-channel-
        # free w.r.t. the actual choice (the verifier already sees the
        # choice at reveal time; this check only binds the commit).
        if len(proof) != 32:
            return False
        for choice in BallotChoice:
            expected = _digest(
                b"acgs-validity-hashcommit-v1",
                self.scheme_id.encode("ascii"),
                statement.epoch,
                statement.subject,
                statement.voter,
                statement.commit,
                statement.nullifier,
                choice.value.encode("ascii"),
            )
            if expected == proof:
                return True
        return False


@runtime_checkable
class ZKSnarkProver(ValidityProver, Protocol):  # pragma: no cover - marker
    """Marker Protocol for a future Groth16/PLONK backend.

    A conforming implementation would:
      * Fix a circuit that checks ``choice ∈ {yea, nay, abstain}`` and
        that ``commit == H("acgs-commit-v2" || choice || nonce || epoch ||
        subject || voter_pub)`` using the module's length-prefixed digest.
      * Run the CRS/trusted-setup once per (epoch, subject) family.
      * Emit a ~200-byte SNARK proof (Groth16) or ~400-byte PLONK proof.

    This module ships the Protocol only; the actual circuit, setup,
    and verifier belong in a dedicated package gated behind an opt-in
    dependency (``arkworks-py``/``gnark``/``snarkjs``).
    """


# ---------------------------------------------------------------------------
# Pure-function primitives
# ---------------------------------------------------------------------------


def _digest(*parts: bytes) -> bytes:
    h = hashlib.sha256()
    for p in parts:
        h.update(len(p).to_bytes(4, "big"))
        h.update(p)
    return h.digest()


def _validate_voter_pub(voter_pub: bytes) -> None:
    if not isinstance(voter_pub, bytes) or len(voter_pub) != 32:
        raise ValueError("voter_pub must be a 32-byte Ed25519 public key")
    try:
        Ed25519PublicKey.from_public_bytes(voter_pub)
    except ValueError as exc:
        raise ValueError(f"invalid Ed25519 public key: {exc}") from exc


def _validate_eligible_voters(eligible_voters: frozenset[bytes]) -> frozenset[bytes]:
    if not isinstance(eligible_voters, frozenset):
        raise TypeError("eligible_voters must be a frozenset of Ed25519 public keys")
    normalized = frozenset(eligible_voters)
    for voter_pub in normalized:
        _validate_voter_pub(voter_pub)
    return normalized


def compute_nullifier(*, voter_pub: bytes, epoch: bytes, subject: bytes) -> bytes:
    """Return the canonical double-vote tag for one registered voter key.

    The keyword-only public-key argument intentionally makes stale
    secret-based calls fail loudly instead of treating a 32-byte secret
    as an Ed25519 identity.
    """
    _validate_voter_pub(voter_pub)
    return _digest(b"acgs-null-v2", voter_pub, epoch, subject)


def _commit_digest(
    choice: BallotChoice,
    nonce: bytes,
    epoch: bytes,
    subject: bytes,
    voter_pub: bytes,
) -> bytes:
    return _digest(
        b"acgs-commit-v2",
        choice.value.encode("ascii"),
        nonce,
        epoch,
        subject,
        voter_pub,
    )


def _signing_payload_commit(
    version: int,
    epoch: bytes,
    subject: bytes,
    voter_pub: bytes,
    commit: bytes,
    nullifier: bytes,
    proof_scheme: str | None,
    validity_proof: bytes | None,
) -> bytes:
    scheme_present = b"\x01" if proof_scheme is not None else b"\x00"
    proof_present = b"\x01" if validity_proof is not None else b"\x00"
    try:
        encoded_proof_scheme = b"" if proof_scheme is None else proof_scheme.encode("utf-8")
    except UnicodeEncodeError as exc:
        raise InvalidCommitError("proof_scheme must be valid UTF-8") from exc
    return _digest(
        b"acgs-commit-sig-v2",
        version.to_bytes(4, "big"),
        epoch,
        subject,
        voter_pub,
        commit,
        nullifier,
        scheme_present,
        encoded_proof_scheme,
        proof_present,
        b"" if validity_proof is None else validity_proof,
    )


def _signing_payload_reveal(commit: bytes, choice: BallotChoice, nonce: bytes) -> bytes:
    return _digest(b"acgs-reveal-sig-v1", commit, choice.value.encode("ascii"), nonce)


# ---------------------------------------------------------------------------
# Record types
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CommitRecord:
    """Published commit to a private vote.

    The ``voter`` field is the Ed25519 public key that signed this
    commit. The registered public key is the voting identity, and the
    canonical nullifier is its auditable epoch/subject double-vote tag.

    v2 records additionally carry ``proof_scheme`` + ``validity_proof``.
    v1 records set both to ``None``. Signatures produced before the
    proof-aware ``acgs-commit-sig-v2`` encoding must be regenerated.
    """

    version: int
    epoch: bytes
    subject: bytes
    voter: bytes  # Ed25519 pubkey raw (32 bytes)
    commit: bytes  # 32 bytes
    nullifier: bytes  # 32 bytes
    signature: bytes  # 64 bytes
    proof_scheme: str | None = None
    validity_proof: bytes | None = None

    def to_dict(self) -> dict[str, str | int | None]:
        out: dict[str, str | int | None] = {
            "version": self.version,
            "epoch": self.epoch.hex(),
            "subject": self.subject.hex(),
            "voter": self.voter.hex(),
            "commit": self.commit.hex(),
            "nullifier": self.nullifier.hex(),
            "signature": self.signature.hex(),
        }
        if self.version >= _V2_VERSION:
            out["proof_scheme"] = self.proof_scheme
            out["validity_proof"] = (
                self.validity_proof.hex() if self.validity_proof is not None else None
            )
        return out

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), sort_keys=True)

    @classmethod
    def from_dict(cls, data: Mapping[str, object]) -> CommitRecord:
        try:
            version = int(data["version"])  # type: ignore[call-overload]
            proof_scheme: str | None = None
            validity_proof: bytes | None = None
            if version >= _V2_VERSION:
                raw_scheme = data.get("proof_scheme")
                proof_scheme = None if raw_scheme is None else str(raw_scheme)
                raw_proof = data.get("validity_proof")
                validity_proof = None if raw_proof is None else bytes.fromhex(str(raw_proof))
            return cls(
                version=version,
                epoch=bytes.fromhex(str(data["epoch"])),
                subject=bytes.fromhex(str(data["subject"])),
                voter=bytes.fromhex(str(data["voter"])),
                commit=bytes.fromhex(str(data["commit"])),
                nullifier=bytes.fromhex(str(data["nullifier"])),
                signature=bytes.fromhex(str(data["signature"])),
                proof_scheme=proof_scheme,
                validity_proof=validity_proof,
            )
        except (KeyError, ValueError, TypeError) as exc:
            raise InvalidCommitError(f"malformed commit dict: {exc}") from exc


@dataclass(frozen=True)
class RevealRecord:
    """Published reveal for a prior commit."""

    version: int
    commit: bytes
    choice: BallotChoice
    nonce: bytes
    signature: bytes  # Ed25519 sig over the reveal payload

    def to_dict(self) -> dict[str, str | int]:
        return {
            "version": self.version,
            "commit": self.commit.hex(),
            "choice": self.choice.value,
            "nonce": self.nonce.hex(),
            "signature": self.signature.hex(),
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), sort_keys=True)

    @classmethod
    def from_dict(cls, data: Mapping[str, object]) -> RevealRecord:
        try:
            return cls(
                version=int(data["version"]),  # type: ignore[call-overload]
                commit=bytes.fromhex(str(data["commit"])),
                choice=BallotChoice(str(data["choice"])),
                nonce=bytes.fromhex(str(data["nonce"])),
                signature=bytes.fromhex(str(data["signature"])),
            )
        except (KeyError, ValueError, TypeError) as exc:
            raise InvalidRevealError(f"malformed reveal dict: {exc}") from exc


# ---------------------------------------------------------------------------
# Builders
# ---------------------------------------------------------------------------


def build_commit(
    *,
    voter_private_key: Ed25519PrivateKey,
    voter_secret: bytes,
    epoch: bytes,
    subject: bytes,
    choice: BallotChoice,
    nonce: bytes | None = None,
    prover: ValidityProver | None = None,
) -> tuple[CommitRecord, RevealRecord]:
    """Create a commit + matching reveal for a single voter.

    The reveal is *not yet signed* with the commit field filled in
    because we need to produce both atomically. Returns both; the
    voter publishes ``commit`` now and ``reveal`` in the reveal phase.

    If ``prover`` is supplied the commit is emitted as a v2 record
    carrying a ``validity_proof`` attesting that the committed choice
    is a well-formed :class:`BallotChoice`. When ``prover`` is None
    the legacy v1 format is used.
    """
    if nonce is None:
        nonce = secrets.token_bytes(32)
    if len(nonce) < 16:
        raise ValueError("nonce must be at least 16 bytes")

    from cryptography.hazmat.primitives import serialization as _ser  # local

    voter_pub_raw = voter_private_key.public_key().public_bytes(
        encoding=_ser.Encoding.Raw,
        format=_ser.PublicFormat.Raw,
    )
    commit_digest = _commit_digest(choice, nonce, epoch, subject, voter_pub_raw)
    nullifier = compute_nullifier(voter_pub=voter_pub_raw, epoch=epoch, subject=subject)

    reveal_sig = voter_private_key.sign(_signing_payload_reveal(commit_digest, choice, nonce))

    proof_scheme: str | None = None
    validity_proof: bytes | None = None
    record_version = _RECORD_VERSION
    if prover is not None:
        statement = ValidityStatement(
            epoch=epoch,
            subject=subject,
            voter=voter_pub_raw,
            commit=commit_digest,
            nullifier=nullifier,
        )
        witness = ValidityWitness(choice=choice, nonce=nonce, voter_secret=voter_secret)
        validity_proof = prover.prove(statement, witness)
        proof_scheme = prover.scheme_id
        record_version = _V2_VERSION

    commit_sig = voter_private_key.sign(
        _signing_payload_commit(
            record_version,
            epoch,
            subject,
            voter_pub_raw,
            commit_digest,
            nullifier,
            proof_scheme,
            validity_proof,
        )
    )

    commit_record = CommitRecord(
        version=record_version,
        epoch=epoch,
        subject=subject,
        voter=voter_pub_raw,
        commit=commit_digest,
        nullifier=nullifier,
        signature=commit_sig,
        proof_scheme=proof_scheme,
        validity_proof=validity_proof,
    )
    reveal_record = RevealRecord(
        version=record_version,
        commit=commit_digest,
        choice=choice,
        nonce=nonce,
        signature=reveal_sig,
    )
    return commit_record, reveal_record


def build_reveal(
    *,
    voter_private_key: Ed25519PrivateKey,
    commit: bytes,
    choice: BallotChoice,
    nonce: bytes,
) -> RevealRecord:
    """Create a reveal record for a previously built commit."""
    reveal_sig = voter_private_key.sign(_signing_payload_reveal(commit, choice, nonce))
    return RevealRecord(
        version=_RECORD_VERSION,
        commit=commit,
        choice=choice,
        nonce=nonce,
        signature=reveal_sig,
    )


# ---------------------------------------------------------------------------
# Validation + tally
# ---------------------------------------------------------------------------


def _verify_commit_signature(record: CommitRecord) -> None:
    try:
        pub = Ed25519PublicKey.from_public_bytes(record.voter)
    except ValueError as exc:
        raise InvalidCommitError(f"bad voter pubkey: {exc}") from exc
    payload = _signing_payload_commit(
        record.version,
        record.epoch,
        record.subject,
        record.voter,
        record.commit,
        record.nullifier,
        record.proof_scheme,
        record.validity_proof,
    )
    try:
        pub.verify(record.signature, payload)
    except InvalidSignature as exc:
        raise InvalidCommitError("bad commit signature") from exc


def _validate_commit_record(
    record: CommitRecord,
    *,
    epoch: bytes,
    subject: bytes,
    eligible_voters: frozenset[bytes],
    provers: Mapping[str, ValidityProver],
    strict_v2: bool,
) -> None:
    """Validate every context-bound invariant for a commit record."""
    if record.version not in _SUPPORTED_VERSIONS:
        raise InvalidCommitError(f"unsupported commit version {record.version}")
    if record.epoch != epoch or record.subject != subject:
        raise InvalidCommitError("epoch/subject mismatch")
    if record.voter not in eligible_voters:
        raise InvalidCommitError("ineligible voter")
    try:
        canonical_nullifier = compute_nullifier(
            voter_pub=record.voter, epoch=record.epoch, subject=record.subject
        )
    except ValueError as exc:
        raise InvalidCommitError(str(exc)) from exc
    if record.nullifier != canonical_nullifier:
        raise InvalidCommitError("noncanonical nullifier")
    _verify_commit_signature(record)
    if strict_v2 and record.version < _V2_VERSION:
        raise InvalidCommitError("strict_v2: legacy v1 commit rejected")

    has_scheme = record.proof_scheme is not None
    has_proof = record.validity_proof is not None
    if record.version < _V2_VERSION:
        if has_scheme or has_proof:
            raise InvalidCommitError("v1 commit cannot carry v2 proof fields")
        return
    if has_scheme != has_proof:
        raise InvalidCommitError(
            "v2 commit: proof_scheme and validity_proof must both be set or both absent"
        )
    if has_scheme and (record.proof_scheme == "" or record.validity_proof == b""):
        raise InvalidCommitError("v2 proof_scheme and validity_proof must be non-empty")
    if not has_scheme:
        if strict_v2:
            raise InvalidCommitError("strict_v2 requires proof_scheme and validity_proof")
        return

    assert record.proof_scheme is not None
    assert record.validity_proof is not None
    prover = provers.get(record.proof_scheme)
    if prover is None:
        raise InvalidCommitError(f"no verifier for scheme {record.proof_scheme!r}")
    if prover.scheme_id != record.proof_scheme:
        raise InvalidCommitError(
            f"verifier scheme mismatch: registered {record.proof_scheme!r}, "
            f"verifier declares {prover.scheme_id!r}"
        )
    if strict_v2 and getattr(prover, "provides_validity_assurance", None) is not True:
        raise InvalidCommitError("strict_v2 verifier provides no validity assurance")
    statement = ValidityStatement(
        epoch=record.epoch,
        subject=record.subject,
        voter=record.voter,
        commit=record.commit,
        nullifier=record.nullifier,
    )
    if prover.verify(statement, record.validity_proof) is not True:
        raise InvalidCommitError("invalid validity proof")


def _verify_reveal_against_commit(reveal: RevealRecord, commit_record: CommitRecord) -> None:
    expected = _commit_digest(
        reveal.choice,
        reveal.nonce,
        commit_record.epoch,
        commit_record.subject,
        commit_record.voter,
    )
    if expected != commit_record.commit:
        raise InvalidRevealError("reveal does not open the commit")
    try:
        pub = Ed25519PublicKey.from_public_bytes(commit_record.voter)
    except ValueError as exc:
        raise InvalidRevealError(f"bad voter pubkey: {exc}") from exc
    payload = _signing_payload_reveal(reveal.commit, reveal.choice, reveal.nonce)
    try:
        pub.verify(reveal.signature, payload)
    except InvalidSignature as exc:
        raise InvalidRevealError("bad reveal signature") from exc


@dataclass(frozen=True)
class PrivateTally:
    """Deterministic tally result for an epoch/subject pair."""

    epoch: bytes
    subject: bytes
    totals: Mapping[BallotChoice, int]
    accepted: tuple[bytes, ...] = field(default_factory=tuple)
    rejected: tuple[tuple[bytes, str], ...] = field(default_factory=tuple)

    @property
    def total_valid(self) -> int:
        return sum(self.totals.values())

    def to_dict(self) -> dict[str, object]:
        return {
            "epoch": self.epoch.hex(),
            "subject": self.subject.hex(),
            "totals": {k.value: v for k, v in self.totals.items()},
            "accepted": [c.hex() for c in self.accepted],
            "rejected": [(c.hex(), reason) for c, reason in self.rejected],
        }


def tally(
    commits: Iterable[CommitRecord],
    reveals: Iterable[RevealRecord],
    *,
    epoch: bytes,
    subject: bytes,
    eligible_voters: frozenset[bytes],
    require_all_revealed: bool = False,
    provers: Mapping[str, ValidityProver] | None = None,
    strict_v2: bool = False,
) -> PrivateTally:
    """Audit commits + reveals and produce a deterministic tally.

    Rules:
      * Every commit must belong to an eligible Ed25519 key and carry
        that key's canonical nullifier.
      * Each eligible key contributes at most one ballot.
      * A commit with no matching reveal is counted as missing.
      * Each reveal must open its commit and its signature must verify.
      * Only commits that are accepted *and* have a valid reveal
        contribute to totals.
      * Strict v2 requires a proof and a registered verifier whose
        scheme matches and which explicitly advertises real validity
        assurance.
    """
    eligible_voters = _validate_eligible_voters(eligible_voters)
    commits = list(commits)
    reveals_by_commit: dict[bytes, list[RevealRecord]] = {}
    for rv in reveals:
        # Collect all reveals per commit — the valid one is found during tally.
        reveals_by_commit.setdefault(rv.commit, []).append(rv)

    seen_nullifiers: set[bytes] = set()
    seen_voters: set[bytes] = set()
    accepted: list[tuple[tuple[bytes, bytes], CommitRecord]] = []
    rejected: list[tuple[bytes, str]] = []
    provers_map: Mapping[str, ValidityProver] = provers or {}

    # The voter key breaks digest ties, making first-wins deterministic even
    # when an eligible attacker copies another voter's digest.
    for c in sorted(commits, key=lambda r: (r.commit, r.voter)):
        try:
            _validate_commit_record(
                c,
                epoch=epoch,
                subject=subject,
                eligible_voters=eligible_voters,
                provers=provers_map,
                strict_v2=strict_v2,
            )
        except InvalidCommitError as exc:
            rejected.append((c.commit, str(exc)))
            continue
        if c.voter in seen_voters:
            rejected.append((c.commit, "duplicate voter"))
            continue
        # Defense in depth for future nullifier derivations or a digest collision.
        if c.nullifier in seen_nullifiers:
            rejected.append((c.commit, "duplicate nullifier"))
            continue
        seen_voters.add(c.voter)
        seen_nullifiers.add(c.nullifier)
        accepted.append(((c.voter, c.commit), c))

    totals: dict[BallotChoice, int] = {ch: 0 for ch in BallotChoice}
    tallied_commits: list[bytes] = []
    tallied_ballots: set[tuple[bytes, bytes]] = set()
    digest_counts: dict[bytes, int] = {}
    for _, commit_record in accepted:
        digest_counts[commit_record.commit] = digest_counts.get(commit_record.commit, 0) + 1
    for ballot_id, c in accepted:
        rvs = reveals_by_commit.get(c.commit, [])
        if not rvs:
            reason = "missing reveal"
            if digest_counts[c.commit] > 1:
                reason = f"{reason} for voter {c.voter.hex()}"
            rejected.append((c.commit, reason))
            continue
        # Try all reveals for this commit in arrival order; accept the first valid one.
        verified_rv: RevealRecord | None = None
        last_exc_msg = ""
        for rv in rvs:
            try:
                _verify_reveal_against_commit(rv, c)
                verified_rv = rv
                break
            except InvalidRevealError as exc:
                last_exc_msg = str(exc)
        if verified_rv is None:
            reason = last_exc_msg or "invalid reveal"
            if digest_counts[c.commit] > 1:
                reason = f"{reason} for voter {c.voter.hex()}"
            rejected.append((c.commit, reason))
            continue
        totals[verified_rv.choice] += 1
        tallied_commits.append(c.commit)
        tallied_ballots.add(ballot_id)

    if require_all_revealed:
        # A commit counts as "revealed" only if it has a *valid* reveal that
        # opens it — the presence of a malformed or non-opening reveal (which
        # is dropped in the loop above) does not satisfy the gate.
        missing = [ballot_id for ballot_id, _ in accepted if ballot_id not in tallied_ballots]
        if missing:
            raise MissingRevealError(
                f"{len(missing)} accepted ballots have no valid reveal"
            )

    return PrivateTally(
        epoch=epoch,
        subject=subject,
        totals=totals,
        accepted=tuple(tallied_commits),
        rejected=tuple(rejected),
    )


# ---------------------------------------------------------------------------
# Stateful helper (nice-to-have for tests / integration)
# ---------------------------------------------------------------------------


@dataclass(frozen=True, eq=False)
class PrivateBallotBox:
    """In-memory ballot box tracking commits then reveals for one epoch/subject.

    Thin wrapper around :func:`tally` that enforces the two-phase
    commit/reveal discipline. Useful for tests and for embedding in
    mesh services.
    """

    epoch: bytes
    subject: bytes
    eligible_voters: frozenset[bytes]
    provers: Mapping[str, ValidityProver] | None = field(default=None, repr=False)
    strict_v2: bool = False
    _commits: dict[tuple[bytes, bytes], CommitRecord] = field(
        default_factory=dict, init=False, repr=False, compare=False
    )
    _nullifiers: dict[bytes, tuple[bytes, bytes]] = field(
        default_factory=dict, init=False, repr=False, compare=False
    )
    _voters: dict[bytes, tuple[bytes, bytes]] = field(
        default_factory=dict, init=False, repr=False, compare=False
    )
    _reveals: dict[tuple[bytes, bytes], RevealRecord] = field(
        default_factory=dict, init=False, repr=False, compare=False
    )
    _closed_commits: bool = field(default=False, init=False, repr=False, compare=False)
    _lock: Lock = field(default_factory=Lock, init=False, repr=False, compare=False)

    def __post_init__(self) -> None:
        object.__setattr__(self, "eligible_voters", _validate_eligible_voters(self.eligible_voters))
        configured_provers = {} if self.provers is None else dict(self.provers)
        object.__setattr__(self, "provers", MappingProxyType(configured_provers))

    def submit_commit(self, record: CommitRecord) -> None:
        # Proof verification may invoke third-party code, so perform it before
        # acquiring the state lock. Configuration is immutable after init.
        provers = self.provers
        assert provers is not None
        _validate_commit_record(
            record,
            epoch=self.epoch,
            subject=self.subject,
            eligible_voters=self.eligible_voters,
            provers=provers,
            strict_v2=self.strict_v2,
        )
        ballot_id = (record.voter, record.commit)
        with self._lock:
            if self._closed_commits:
                raise InvalidCommitError("commit phase already closed")
            if ballot_id in self._commits:
                raise InvalidCommitError("duplicate ballot")
            if record.voter in self._voters:
                raise DoubleVoteError("duplicate voter")
            # Defense in depth for future nullifier derivations or a digest collision.
            if record.nullifier in self._nullifiers:
                raise DoubleVoteError("nullifier reuse")
            self._commits[ballot_id] = record
            self._nullifiers[record.nullifier] = ballot_id
            self._voters[record.voter] = ballot_id

    def close_commit_phase(self) -> None:
        with self._lock:
            object.__setattr__(self, "_closed_commits", True)

    def submit_reveal(self, record: RevealRecord) -> None:
        with self._lock:
            if not self._closed_commits:
                raise InvalidRevealError("reveal phase not open")
            candidates = sorted(
                (
                    (ballot_id, commit_record)
                    for ballot_id, commit_record in self._commits.items()
                    if commit_record.commit == record.commit
                ),
                key=lambda item: item[0],
            )
        if not candidates:
            raise InvalidRevealError("no matching commit")

        matched_id: tuple[bytes, bytes] | None = None
        last_error = "reveal does not match any voter-bound commit"
        for ballot_id, commit_record in candidates:
            try:
                _verify_reveal_against_commit(record, commit_record)
                matched_id = ballot_id
                break
            except InvalidRevealError as exc:
                last_error = str(exc)
        if matched_id is None:
            raise InvalidRevealError(last_error)
        with self._lock:
            self._reveals.setdefault(matched_id, record)

    def tally(
        self,
        *,
        require_all_revealed: bool = False,
    ) -> PrivateTally:
        with self._lock:
            commits = tuple(self._commits.values())
            reveals = tuple(self._reveals.values())
        provers = self.provers
        assert provers is not None
        return tally(
            commits,
            reveals,
            epoch=self.epoch,
            subject=self.subject,
            eligible_voters=self.eligible_voters,
            require_all_revealed=require_all_revealed,
            provers=provers,
            strict_v2=self.strict_v2,
        )
